export const POAC_EVALUATION_ITEMS = [
  { srNo: 1, area: "Suitability of vessels checked. (Mooring plans, STS plans and Q88s reviewed)" },
  { srNo: 2, area: "Risk assessments and JPO reviewed" },
  { srNo: 3, area: "Ship standard Questionnaire reviewed" },
  { srNo: 4, area: "Checked if nighttime berthing is allowed" },
  { srNo: 5, area: "Weather forecasts reviewed" },
  { srNo: 6, area: "Traffic Density with regards to STS Location Considered" },
  { srNo: 7, area: "Suitable anchoring location with regard to vessel draft etc" },
  { srNo: 8, area: "Length of hose string requirements checked" },
  { srNo: 9, area: "Copies of valid STS gear equipment certification" },
  { srNo: 10, area: "Information shared with the vessel for arrival and POAC boarding" },
  { srNo: 11, area: "Safety meeting with support craft crew" },
  { srNo: 12, area: "Condition of Fender and Hoses checked" },
  { srNo: 13, area: "Moorings and additional equipment checked (i.e., split pins, bolts, nuts, gaskets, personnel basket)" },
  { srNo: 14, area: "Conditions of hose lifting slings used" },
  { srNo: 15, area: "Transfer of equipment on support craft" },
  { srNo: 16, area: "Safety meeting conducted with crew and Master" },
  { srNo: 17, area: "Communication skills with crew" },
  { srNo: 18, area: "Inspection of Mooring Winches and associated mooring gears" },
  { srNo: 19, area: "Safety awareness" },
  { srNo: 20, area: "Communication with support craft" },
  { srNo: 21, area: "Rigging of Primary /Secondary Fenders" },
  { srNo: 22, area: "Readiness to heave up anchor /Readiness of Mooring stations" },
  { srNo: 23, area: "Navigation warning broadcast" },
  { srNo: 24, area: "Safety Meeting conducted with crew. (Including snap back zone awareness)" },
  { srNo: 25, area: "Approach and Mooring Plan discussed with Master" },
  { srNo: 26, area: "ME Testing prior to use" },
  { srNo: 27, area: "Agreed means of communication VHF Channel" },
  { srNo: 28, area: "Discussed emergency procedures and ME speed -Manoeuvring" },
  { srNo: 29, area: "OCIMF Checklist complied with" },
  { srNo: 30, area: "Proper handover of command" },
  { srNo: 31, area: "Communication with bridge team / exchange of information" },
  { srNo: 32, area: "Regular monitoring of traffic and vessel's speed" },
  { srNo: 33, area: "Control of mooring operation" },
  { srNo: 34, area: "Check status of impressed current system" },
  { srNo: 35, area: "Interaction" },
  { srNo: 36, area: "Status of radars" },
  { srNo: 37, area: "Parallel landing" },
  { srNo: 38, area: "Angle of approach" },
  { srNo: 39, area: "Positioning of vessel" },
  { srNo: 40, area: "Checking helm indicator" },
  { srNo: 41, area: "Manoeuvring vessels to anchor" },
  { srNo: 42, area: "Communication during approach and mooring" },
  { srNo: 43, area: "Safety Meeting conducted with crew" },
  { srNo: 44, area: "Crane's operational readiness and condition" },
  { srNo: 45, area: "Checking manifold connection" },
  { srNo: 46, area: "Cargo hazard precautions explained to crew. (i.e., H2S monitors for personnel)" },
  { srNo: 47, area: "MSDS for the cargo obtained" },
  { srNo: 48, area: "Hose String and gasket connections" },
  { srNo: 49, area: "Safety Meeting conducted with crew. (Including instruction to regularly tend vessel and fender moorings)" },
  { srNo: 50, area: "OCIMF STS Checklists complied" },
  { srNo: 51, area: "Deck rounds and Manifold pressure monitored" },
  { srNo: 52, area: "Authorities informed of completion of transfer" },
  { srNo: 53, area: "Safety meeting conducted with crew" },
  { srNo: 54, area: "Cargo hose draining and hose disconnection" },
  { srNo: 55, area: "Hoses blanked with bolts inward" },
  { srNo: 56, area: "Informed office to arrange support craft for demobilisation" },
  { srNo: 57, area: "Safety Meeting conducted with crew" },
  { srNo: 58, area: "Avoided crossing ahead" },
  { srNo: 59, area: "OCIMF STS Checklists completed" },
  { srNo: 60, area: "Ship handling skills" },
  { srNo: 61, area: "Regular monitoring of Swell and wind direction" },
  { srNo: 62, area: "Unmooring plan discussed" },
  { srNo: 63, area: "Safety meeting conducted with crew" },
  { srNo: 64, area: "Communication skills with crew" },
  { srNo: 65, area: "Offloading hoses to the support craft" },
  { srNo: 66, area: "De-rigging Primary /Secondary Fenders" },
  { srNo: 67, area: "Control during operations" },
  { srNo: 68, area: "Weather forecasts reviewed regularly" },
  { srNo: 69, area: "Care of STS equipment" },
  { srNo: 70, area: "Use of PPE" },
  { srNo: 71, area: "General Safety awareness" },
  { srNo: 72, area: "Regular operational updates" },
  { srNo: 73, area: "Timely reporting of issues (Advisement of issues in good time to allow for prompt action)" },
  { srNo: 74, area: "General communication with Operations Team" },
  { srNo: 75, area: "Correctly completing and efficiently submitting STS documentation" },
];

export const EVALUATION_CATEGORIES = [
  { name: "Prior to commencement of Operations", start: 1, end: 9 },
  { name: "Mobilization", start: 10, end: 15 },
  { name: "Rigging of vessel", start: 16, end: 23 },
  { name: "Approach and mooring operation", start: 24, end: 42 },
  { name: "Hose connection", start: 43, end: 48 },
  { name: "Cargo operations", start: 49, end: 51 },
  { name: "Hose draining and disconnection", start: 52, end: 56 },
  { name: "Unmooring", start: 57, end: 62 },
  { name: "De-Mobilization", start: 63, end: 66 },
  { name: "General", start: 67, end: 71 },
  { name: "Office Requirements", start: 72, end: 75 },
];
